apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins/jenkins-jenkins-agent: "true"
spec:
  containers:
  - name: "maven"
    # Upgraded this from openjdk-11 to eclipse-temurin-17 to support Spring Boot 3.4.10
    image: "maven:3.9.6-eclipse-temurin-17"
    command:
    - "sleep"
    args:
    - "99d"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - name: "snyk"
    image: "snyk/snyk:maven"
    command:
    - "sleep"
    args:
    - "99d"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - name: "kaniko"
    image: "gcr.io/kaniko-project/executor:debug"
    command:
    - "sleep"
    args:
    - "99d"
    volumeMounts:
    - mountPath: "/kaniko/.docker"
      name: "harbor-creds"
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  volumes:
  - name: "harbor-creds"
    secret:
      items:
      - key: ".dockerconfigjson"
        path: "config.json"
      secretName: "harbor-creds"
  - name: "workspace-volume"
    emptyDir: {}
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ['cat']
    tty: true
